name: ocenifilm
registry: quiirex
# ingress:
#  - name: ingress
#    bindings:
#      - port: 8080
#    rules:
#      - path: /ocenifilmfrontend
#        service: ocenifilmfrontend
services:
- name: identiteta-api
  project: Identiteta.API/Identiteta.API.csproj
  replicas: 1
  #bindings:
  #- port: 7165
- name: igralci-api
  project: Igralci.API/Igralci.API.csproj
  replicas: 1
  #bindings:
  #- port: 7025
- name: komentiranje-api
  project: Komentiranje.API/Komentiranje.API.csproj
  replicas: 1
  #bindings:
  #- port: 7101
- name: videoteka-api
  project: Videoteka.API/Videoteka.API.csproj
  replicas: 1
  #bindings:
  #- port: 7145
- name: seznami-api
  project: Seznami.API/Seznami.API.csproj
  replicas: 1
  #bindings:
  #- port: 7019
- name: ocenjevanje-api
  project: Ocenjevanje.API/Ocenjevanje.API.csproj
  replicas: 1
  #bindings:
  #- port: 7088
- name: ocenifilmfrontend
  project: OceniFilm/OceniFilm.csproj
  replicas: 1
  #bindings:
  #- port: 7080
#SQL Servers
#- name: sqlserver-identiteta
#  image: mcr.microsoft.com/mssql/server:2019-latest 
#  env:
#  - name: SA_PASSWORD
#    value: "IdentitetaM!cr0s3rv!ce"
#  - name: ACCEPT_EULA
#    value: 'Y'
#  volumes:
#  - name: identiteta-storage
#    target: /var/opt/mssql
#  bindings:
#  - port: 1430
#    connectionString: Server=${host};User Id=sa;Database=IdentitetaDB;Password=${env:SA_PASSWORD};
#- name: sqlserver-igralci
#  image: mcr.microsoft.com/mssql/server:2019-latest 
#  env:
#  - name: SA_PASSWORD
#    value: "IgralciM!cr0s3rv!ce"
#  - name: ACCEPT_EULA
#    value: 'Y'
#  volumes:
#  - name: igralci-storage
#    target: /var/opt/mssql
#  bindings:
#  - port: 1431
#    connectionString: Server=${host};User Id=sa;Database=IgralciDB;Password=${env:SA_PASSWORD};
#- name: sqlserver-komentiranje
#  image: mcr.microsoft.com/mssql/server:2019-latest 
#  env:
#  - name: SA_PASSWORD
#    value: "KomentiranjeM!cr0s3rv!ce"
#  - name: ACCEPT_EULA
#    value: 'Y'
#  volumes:
#  - name: komentiranje-storage
#    target: /var/opt/mssql
#  bindings:
#  - port: 1432
#    connectionString: Server=${host};User Id=sa;Database=KomentiranjeDB;Password=${env:SA_PASSWORD};
#- name: sqlserver-ocenjevanje
#  image: mcr.microsoft.com/mssql/server:2019-latest 
#  env:
#  - name: SA_PASSWORD
#    value: "OcenjevanjeM!cr0s3rv!ce"
#  - name: ACCEPT_EULA
#    value: 'Y'
#  volumes:
#  - name: ocenjevanje-storage
#    target: /var/opt/mssql
#  bindings:
#  - port: 1433
#    connectionString: Server=${host};User Id=sa;Database=OcenjevanjeDB;Password=${env:SA_PASSWORD};
#- name: sqlserver-seznami
#  image: mcr.microsoft.com/mssql/server:2019-latest 
#  env:
#  - name: SA_PASSWORD
#    value: "SeznamiM!cr0s3rv!ce"
#  - name: ACCEPT_EULA
#    value: 'Y'
#  volumes:
#  - name: seznami-storage
#    target: /var/opt/mssql
#  bindings:
#  - port: 1434
#    connectionString: Server=${host};User Id=sa;Database=SeznamiDB;Password=${env:SA_PASSWORD};
- name: sqlserver-videoteka
  image: mcr.microsoft.com/mssql/server:2019-latest 
  env:
  - name: SA_PASSWORD
    value: "M!cr0s3rv!ce"
  - name: ACCEPT_EULA
    value: 'Y'
  #volumes:
  #- name: videoteka-storage
  #  target: /var/opt/mssql
  bindings:
  - containerPort: 1433
    connectionString: Server=${host},${port};Database=VideotekaDB;User Id=sa;Password=${env:SA_PASSWORD};
#- name: ocelotapigw
#  project: OcelotApiGw/OcelotApiGw.csproj
#  bindings:
#  - port: 7248
