// <auto-generated />
using System;
using Komentiranje.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Komentiranje.API.Migrations
{
    [DbContext(typeof(KomentiranjeDbContext))]
    [Migration("20220510101146_firstmigration")]
    partial class firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Komentiranje.API.Models.Komentar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DatumZapisa")
                        .HasColumnType("datetime2");

                    b.Property<int>("KomentatorId")
                        .HasColumnType("int");

                    b.Property<int>("KomentiranFilmId")
                        .HasColumnType("int");

                    b.Property<string>("Vsebina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KomentatorId");

                    b.HasIndex("KomentiranFilmId");

                    b.ToTable("Komentarji");
                });

            modelBuilder.Entity("Komentiranje.API.Models.Komentator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("PrikaznoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Komentator");
                });

            modelBuilder.Entity("Komentiranje.API.Models.KomentiranFilm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KomentiranFilm");
                });

            modelBuilder.Entity("Komentiranje.API.Models.Komentar", b =>
                {
                    b.HasOne("Komentiranje.API.Models.Komentator", "Komentator")
                        .WithMany()
                        .HasForeignKey("KomentatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Komentiranje.API.Models.KomentiranFilm", "KomentiranFilm")
                        .WithMany()
                        .HasForeignKey("KomentiranFilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Komentator");

                    b.Navigation("KomentiranFilm");
                });
#pragma warning restore 612, 618
        }
    }
}
